version: "3"
services:
    instagram:
        build: 
            context: ../
            dockerfile: ./docker/Dockerfile
        command: uvicorn main:app --host 0.0.0.0 --port 8080 --log-config log.ini
        ports:
            - 8080:8080